import type { Metadata } from "next";
import { Alata, Playfair_Display, Roboto } from "next/font/google";
import "./globals.css";

const PlayfairDisplay = Playfair_Display({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: "100"
});
const alata = Alata({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${PlayfairDisplay.className} ${alata.style.fontFamily} 
      ${roboto.style.fontFamily}`}>{children}</body>
    </html>
  );
}
