import type { Metadata } from "next";
import { Alata, Playfair_Display, Roboto } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const PlayfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: "100",
  variable: "--font-roboto",
});
const alata = Alata({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-alata",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PlayfairDisplay.variable} ${roboto.variable} ${alata.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
